// ─────────────────────────────────────────────────────────────────────────────
//  AUTO-GENERATED by scripts/fetch-wc-data.mjs — do not edit by hand.
//  Last fetched: 2026-06-14
//  Source: ESPN public API
// ─────────────────────────────────────────────────────────────────────────────

export interface DraftPick {
  team: string;
  owner: string;
  flag: string;
}

export const draft: DraftPick[] = [
  { team: "Brazil", owner: "Sammy", flag: "🇧🇷" },
  { team: "Morocco", owner: "James", flag: "🇲🇦" },
  { team: "Spain", owner: "Dan", flag: "🇪🇸" },
  { team: "France", owner: "Sam", flag: "🇫🇷" },
  { team: "England", owner: "Brendan", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { team: "Portugal", owner: "Jared", flag: "🇵🇹" },
  { team: "Argentina", owner: "Ben", flag: "🇦🇷" },
  { team: "Germany", owner: "Aaron", flag: "🇩🇪" },
  { team: "Netherlands", owner: "Matt", flag: "🇳🇱" },
  { team: "Belgium", owner: "Mike", flag: "🇧🇪" },
  { team: "Norway", owner: "Scott", flag: "🇳🇴" },
  { team: "Colombia", owner: "Nathan", flag: "🇨🇴" },
];

export interface Result {
  matchday: number;
  team: string;
  opponent: string;
  scoreFor: number;
  scoreAgainst: number;
  goals: string[];
  assists: number;
  cleanSheet: boolean;
  yellowCards: string[];
  redCards: string[];
  ownGoals: string[];
}

export const results: Result[] = [
  {
    matchday: 1,
    team: "Brazil",
    opponent: "Morocco",
    scoreFor: 1,
    scoreAgainst: 1,
    goals: ["Vinícius Júnior"],
    assists: 1,
    cleanSheet: false,
    yellowCards: ["Casemiro","Roger Ibañez"],
    redCards: [],
    ownGoals: [],
  },
  {
    matchday: 1,
    team: "Morocco",
    opponent: "Brazil",
    scoreFor: 1,
    scoreAgainst: 1,
    goals: ["Ismael Saibari"],
    assists: 1,
    cleanSheet: false,
    yellowCards: [],
    redCards: [],
    ownGoals: [],
  },
];

export interface Fixture {
  matchday: number;
  team: string;
  opponent: string;
  kickoff?: string;
}

export const fixtures: Fixture[] = [
  { matchday: 1, team: "Argentina", opponent: "Algeria", kickoff: "Wed 01:00 UTC" },
  { matchday: 1, team: "Belgium", opponent: "Egypt", kickoff: "Mon 19:00 UTC" },
  { matchday: 1, team: "Colombia", opponent: "Uzbekistan", kickoff: "Thu 02:00 UTC" },
  { matchday: 1, team: "England", opponent: "Croatia", kickoff: "Wed 20:00 UTC" },
  { matchday: 1, team: "France", opponent: "Senegal", kickoff: "Tue 19:00 UTC" },
  { matchday: 1, team: "Germany", opponent: "Curaçao", kickoff: "Sun 17:00 UTC" },
  { matchday: 1, team: "Netherlands", opponent: "Japan", kickoff: "Sun 20:00 UTC" },
  { matchday: 1, team: "Norway", opponent: "Iraq", kickoff: "Tue 22:00 UTC" },
  { matchday: 1, team: "Portugal", opponent: "Congo DR", kickoff: "Wed 17:00 UTC" },
  { matchday: 1, team: "Spain", opponent: "Cape Verde", kickoff: "Mon 16:00 UTC" },
  { matchday: 2, team: "Argentina", opponent: "Austria", kickoff: "Mon 17:00 UTC" },
  { matchday: 2, team: "Belgium", opponent: "Iran", kickoff: "Sun 19:00 UTC" },
  { matchday: 2, team: "Brazil", opponent: "Haiti", kickoff: "Sat 00:30 UTC" },
  { matchday: 2, team: "Colombia", opponent: "Congo DR", kickoff: "Wed 02:00 UTC" },
  { matchday: 2, team: "England", opponent: "Ghana", kickoff: "Tue 20:00 UTC" },
  { matchday: 2, team: "France", opponent: "Iraq", kickoff: "Mon 21:00 UTC" },
  { matchday: 2, team: "Germany", opponent: "Ivory Coast", kickoff: "Sat 20:00 UTC" },
  { matchday: 2, team: "Morocco", opponent: "Scotland", kickoff: "Fri 22:00 UTC" },
  { matchday: 2, team: "Netherlands", opponent: "Sweden", kickoff: "Sat 17:00 UTC" },
  { matchday: 2, team: "Norway", opponent: "Senegal", kickoff: "Tue 00:00 UTC" },
  { matchday: 2, team: "Portugal", opponent: "Uzbekistan", kickoff: "Tue 17:00 UTC" },
  { matchday: 2, team: "Spain", opponent: "Saudi Arabia", kickoff: "Sun 16:00 UTC" },
  { matchday: 3, team: "Argentina", opponent: "Jordan", kickoff: "Sun 02:00 UTC" },
  { matchday: 3, team: "Belgium", opponent: "New Zealand", kickoff: "Sat 03:00 UTC" },
  { matchday: 3, team: "Brazil", opponent: "Scotland", kickoff: "Wed 22:00 UTC" },
  { matchday: 3, team: "Colombia", opponent: "Portugal", kickoff: "Sat 23:30 UTC" },
  { matchday: 3, team: "England", opponent: "Panama", kickoff: "Sat 21:00 UTC" },
  { matchday: 3, team: "France", opponent: "Norway", kickoff: "Fri 19:00 UTC" },
  { matchday: 3, team: "Germany", opponent: "Ecuador", kickoff: "Thu 20:00 UTC" },
  { matchday: 3, team: "Morocco", opponent: "Haiti", kickoff: "Wed 22:00 UTC" },
  { matchday: 3, team: "Netherlands", opponent: "Tunisia", kickoff: "Thu 23:00 UTC" },
  { matchday: 3, team: "Norway", opponent: "France", kickoff: "Fri 19:00 UTC" },
  { matchday: 3, team: "Portugal", opponent: "Colombia", kickoff: "Sat 23:30 UTC" },
  { matchday: 3, team: "Spain", opponent: "Uruguay", kickoff: "Sat 00:00 UTC" },
];

export const lastUpdated = "Auto-updated 2026-06-14 via ESPN";
